### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by minanagehsalalma** [cakemanny/upnp-tools#2]
```
Exception happened during processing of request from ('127.0.0.1', 2498)
Traceback (most recent call last):
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 717, in __init__
    self.handle()
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\Potato\Downloads\Compressed\upnp-tools-master\run.py", line 123, in do_GET
    redis = RedisClient()
  File "C:\Users\Potato\Downloads\Compressed\upnp-tools-master\redis.py", line 7, in __init__
    self.s.connect(addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

Googling The error showed this as a solution

> [Must start server before client. if no server running, the client will meet ConnectionRefusedError](https://github.com/Lawouach/WebSocket-for-Python/issues/130).

Tried the fix by running redis.py first then run.py but still same error 

other than that everything works out fine

**Comment by minanagehsalalma** [comment]
Testing it on Kali the error changed to 111

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
listening at http://127.0.0.1:8000/
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Potato/Downloads/upnp-tools-master/run.py", line 183, in listen
    redis = RedisClient()
  File "/home/Potato/Downloads/upnp-tools-master/redis.py", line 7, in __init__
    self.s.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused
127.0.0.1 - - [04/Feb/2022 13:33:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Feb/2022 13:33:30] "GET /main.css HTTP/1.1" 200 -
127.0.0.1 - - [04/Feb/2022 13:33:30] "GET /main.js HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 52850)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/home/Potato/Downloads/upnp-tools-master/run.py", line 123, in do_GET
    redis = RedisClient()
  File "/home/Potato/Downloads/upnp-tools-master/redis.py", line 7, in __init__
    self.s.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused

```

**Comment by cakemanny** [comment]
Are you running an instance of redis ?

Perhaps I should make those errors a bit quieter, if it's not possible to connect to redis...

**Comment by cakemanny** [comment]
Kali is Ubuntu based right? So I figure you need to
```
sudo apt install redis-server
sudo systemctl start redis
```

**Comment by minanagehsalalma** [comment]
> Are you running an instance of redis ?
> 
> Perhaps I should make those errors a bit quieter, if it's not possible to connect to redis...

Before run.py

I ran redis.py

is this how you should be doing it ?

**Comment by cakemanny** [comment]
`redis.py` simply contains the client code for talking to a redis server.
You can install the server via your package manager or from https://redis.io/ 

Here it's only used for seeing the SSDP announcements made on the network. Which would appear in the **Notifications** panel on the right
![image](https://user-images.githubusercontent.com/4025945/152594687-a58c6668-0335-4e33-a5da-91dba432e64c.png)

I've made the errors a little quieter in b438d2e6e819f53900843edc1288e6c8f7ca0d59 , since it does say in the readme that this part is optional.

**Comment by minanagehsalalma** [comment]
> I've made the errors a little quieter in [b438d2e](https://github.com/cakemanny/upnp-tools/commit/b438d2e6e819f53900843edc1288e6c8f7ca0d59) , since it does say in the readme that this part is optional.

oh Now it's a lot better thanks : )
