### ISSUE TITLE
Add Auth digest support ?

### ISSUE THREAD

**Issue by minanagehsalalma** [cakemanny/upnp-tools#3]
All the important actions Require [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) header

It can be doing using url like this
`curl -v  'https://jigsaw.w3.org/HTTP/Digest/' --digest -u guest:guest --form data=test
`
The default username and password for almost all devices is 

`dslf-config:admin`
![Auth1](https://user-images.githubusercontent.com/20546638/152574691-b8a4b72e-55af-42ad-bc82-a578a465589f.JPG)
![auth2](https://user-images.githubusercontent.com/20546638/152574695-ddc7b1cb-26f7-4726-843b-f83cd04afabf.JPG)

Curl 
![image](https://user-images.githubusercontent.com/20546638/152574931-33cd274f-fd00-483e-b988-57c0c05e376e.png)

**Comment by minanagehsalalma** [comment]
@cakemanny in python it can be done like that 

```
import requests
from requests.auth import HTTPDigestAuth

data = '''<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<SOAP-ENV:Body><m:GetSoftwareVersion xmlns:m="urn:www-huawei-com:service:DeviceUpgrade:1"/>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
'''
Send = requests.post('http://192.168.1.1:37215/ctrlt/DeviceUpgrade_1', auth=HTTPDigestAuth('dslf-config', 'admin'),data=data)
print(Send.text)
```

Ex. From [docs.python : Digest Authentication](https://docs.python-requests.org/en/latest/user/authentication/#digest-authentication)

![image](https://user-images.githubusercontent.com/20546638/152577783-c36a9381-c037-4985-91ee-7e5baf6cd41d.png)

**Comment by minanagehsalalma** [comment]
@cakemanny  Even That i don't know python , I tried Really hard for a couple of hours
and I add a temporary work around , 
But i Couldn't Get it to post to the http server but only the command line 

```
            try:
                print('getting response')
                f = conn.getresponse()                               
                if f.status == 401:
#ADD YOUR PASSWORD AND USERNAME BY REPLACING dslf-config with the username and admin with the password and if you don't know them or you didn't change them then leave them as they are default in most cases                 	
               	 print('                                                            Warning Auth Required IF You Didnt add Your password Yet then Add it          ')
               	 conn = requests.post("http://"+parts.netloc+self.path_and_query(location), headers=headers, data=body,auth=HTTPDigestAuth('dslf-config', 'admin'))
               	 print(self.send_response(HTTPStatus(f.status)))
                 print('copying response')
                 xmll = xml.dom.minidom.parseString(conn.text)
                 xml_pretty_str = xmll.toprettyxml()
                 print(xml_pretty_str)
                 shutil.copyfileobj(conn, self.wfile)
                else: 
                 print(self.send_response(HTTPStatus(f.status)))
                 self.send_header('Content-Type', f.getheader('Content-Type'))
                 if f.getheader('Content-Length'):
                    self.send_header('Content-Length', f.getheader('Content-Length'))
                 self.end_headers()
                 print('copying response')
                 shutil.copyfileobj(f, self.wfile)

```
And imported these libs 
```
import requests
from requests.auth import HTTPDigestAuth
import xml.dom.minidom
```
I added an IF statement that if the http error is 401 then do A `python requests` method instead of the `HTTPConnection  `method  since i wasn't able to find how to do the Digest auth in it... otherwise it does the requests the normal methods 
![image](https://user-images.githubusercontent.com/20546638/152625836-828392e5-1144-4b83-8a64-eecaa7956eda.png)

I am Getting this error since requests isn't An object of type HTTPResponse Therefore it doesn't have  'read' attribute and i couldn't find the API to modify it 
```
Exception happened during processing of request from ('127.0.0.1', 8040)
Traceback (most recent call last):
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 717, in __init__
    self.handle()
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\Potato\Downloads\Compressed\later\UPNP\upnp-tools-master\run.py", line 192, in do_POST
    shutil.copyfileobj(conn, self.wfile)
  File "C:\Users\Potato\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
AttributeError: 'Response' object has no attribute 'read'
```

**other problems :**
This will Slow it down and send more not needed Requested instead of only sending the Digest Header as second request when `Http error 401 Not authorized happen` as  it sends it as a third request since the I couldn't add Digest auth in First one and now i am using it for the 401 check

Also errors may happen in the URL part since i wasn't able to figure how to do the URL formatting you used so i had to marge them all haha
` conn = requests.post("http://"+parts.netloc+self.path_and_query(location), headers=headers, data=body,auth=HTTPDigestAuth('dslf-config', 'admin'))
` 

Note : When the option is Specified in an argument. Curl and i believe almost all tools Does it this way 

> curl should automatically perform an initial request with empty content, extract the authentication parameters and then repeat the request with that information, the credentials and the content.



Thanksssssssss a lot

**Comment by cakemanny** [comment]
Ahh, nice progress.
Hmm. Yeah, I'm not sure why I used `http.client.HTTPConnection`. I know I didn't want to use `requests` because I wanted to avoid people having to install extra dependencies. But I could have used [`urllib.request`](https://docs.python.org/3.7/library/urllib.request.html) which does have an [`HTTPDigestAuthHandler`](https://docs.python.org/3.7/library/urllib.request.html#urllib.request.HTTPDigestAuthHandler)

I'm not sure I have time to work on this right now. I would definitely like to at some point though.

However, you should be able to get your edits working with the following small change:

```diff
 conn = requests.post("http://"+parts.netloc+self.path_and_query(location), headers=headers, data=body,auth=HTTPDigestAuth('dslf-config', 'admin'))
-print(self.send_response(HTTPStatus(f.status)))
+print(self.send_response(HTTPStatus(conn.status_code)))
 print('copying response')
 xmll = xml.dom.minidom.parseString(conn.text)
 xml_pretty_str = xmll.toprettyxml()
 print(xml_pretty_str)
-shutil.copyfileobj(conn, self.wfile)
+f = io.BytesIO(conn.content)
+shutil.copyfileobj(f, self.wfile)
```
and adding the import for `io`
```
import io
```
